global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ] # Update with the correct host and port for your Spring Boot application
  - job_name: 'eureka-server'
    static_configs:
      - targets: [ 'host.docker.internal:8761' ]