server:
  port: 6000
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: payment-method-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment-method/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
        - id: payment_route
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
        - id: order-payment-service
          uri: lb://order-payment-service
          predicates:
            - Path=/api/order-payment/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: fast-payment
            client-secret: YV7BQhesXAof0e0vgHdXZc4tkddJ4Zby
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email

        provider:
          keycloak:
            issuer-uri: http://localhost:7000/realms/fast-payment
            user-info-uri: http://localhost:7000/realms/fast-payment/protocol/openid-connect/userinfo
            token-uri: http://localhost:7000/realms/fast-payment/protocol/openid-connect/token
            authorization-uri: http://localhost:7000/realms/fast-payment/protocol/openid-connect/auth
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7000/realms/fast-payment
          jwk-set-uri: http://localhost:7000/realms/fast-payment/protocol/openid-connect/certs
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        cloud:
          gateway: DEBUG
        boot:
          web:
            servlet:
              FilterRegistrationBean: TRACE
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.64:8761/eureka/