apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: bickyrajkayastha/fast-payment-config-server:aabc3634e95771e0d3136a1d5a3701186c9fe147
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
