apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: bickyrajkayastha/fast-payment-config-server:f1e1024474c33f4c89c2f26f3e612f7c9d6a06c6
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
