apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: bickyrajkayastha/fast-payment-config-server:f459f98cd865546b7e7cf86abb2e65be47473352
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
