apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: bickyrajkayastha/fast-payment-config-server:023fcbe088c7ac04a0962d7b56730a4d16de501a
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
