apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888         # Exposes the service on port 80
      targetPort: 8888  # The port on the container
#      nodePort: 31000
  selector:
    app: config-server
