apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7024         # Exposes the service on port 80
      targetPort: 7024  # The port on the container
#      nodePort: 31000
  selector:
    app: user-service
