apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: bickyrajkayastha/fast-payment-eureka-service:dde1051c64cd2096d5eaafd6ef2f420a1a2505b8
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
