apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  labels:
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - name: service-registry
        image: bickyrajkayastha/fast-payment-service-registry:2dcc73bc7b270e5577811c86bfe54e2a08a262cc
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
