apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: bickyrajkayastha/fast-payment-eureka-service:3cfea09902be7e105d3e48d5c38b5d93ae26b4b0
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
