apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  labels:
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - name: service-registry
        image: bickyrajkayastha/fast-payment-service-registry:c235812db81a17d6b68cdfc2e9151c11d710c599
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
