apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80         # Exposes the service on port 80
      targetPort: 8761  # The port on the container
      nodePort: 30002
  selector:
    app: eureka-service
