apiVersion: v1
kind: Service
metadata:
  name: service-registry
  labels:
    app: service-registry
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80         # Exposes the service on port 80
      targetPort: 8761  # The port on the container
      nodePort: 30002
  selector:
    app: service-registry
