server:
  port: 7073
spring:
  application:
    name: payment-service
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .html
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    mode: HTML
  datasource:
    url: jdbc:postgresql://localhost:5432/demospring_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: fast-payment
            client-secret: qKUDaUnHWfLJiarO1pWfnQoyKJyDwZqC
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:7000/realms/fast-payment
            user-info-uri: http://localhost:7000/realms/fast-payment/protocol/openid-connect/userinfo
            token-uri: http://localhost:7000/realms/fast-payment/protocol/openid-connect/token
            authorization-uri: http://localhost:7000/realms/fast-payment/protocol/openid-connect/auth
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7000/auth/realms/fast-payment
          jwk-set-uri: http://localhost:7000/auth/realms/fast-payment/protocol/openid-connect/certs
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: OFF
        orm:
          jdbc:
            bind: OFF
      springframework:
        web: DEBUG
        security: DEBUG
        cloud:
          gateway: DEBUG
        boot:
          web:
            servlet:
              FilterRegistrationBean: TRACE

keycloak:
  realm: fast-payment
  auth-server-url: http://localhost:7000
  resource: fast-payment
  credentials:
    secret: YV7BQhesXAof0e0vgHdXZc4tkddJ4Zby
  public-client: true
  use-resource-role-mappings: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

stripe:
  api:
    key: sk_test_51Py2m9ILN8lgkSQJJbkrFO6IaprfP906cHTh9qwjpAJ7JHg8uGVujiGvGEAkW0TvpYAhEIFqJ3Fv6q0OWKBiYfrB00k2tvF80N
  webhook:
    secret: whsec_cviqtLOmTrmtxM7TtXK2EvLgUp88sh0c
#    secret: whsec_9af87e9602cf68113799a3c5760ff70debe3012d2719ae24776e9ebde7e35194