apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7071         # Exposes the service on port 80
      targetPort: 7071  # The port on the container
#      nodePort: 31000
  selector:
    app: product-service
