spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/demospring_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Options: validate | update | create | create-drop

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: fast-payment
            client-secret: 3dUyOoZlIakzZiZ3QqPyIA73dcFC3Z5D
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: "openid,profile,email"
        provider:
          keycloak:
            issuer-uri: http://localhost:9065/realms/fast-payment
            user-info-uri: http://localhost:9065/realms/fast-payment/protocol/openid-connect/userinfo
            token-uri: http://localhost:9065/realms/fast-payment/protocol/openid-connect/token
            authorization-uri: http://localhost:9065/realms/fast-payment/protocol/openid-connect/auth
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9065/auth/realms/fast-payment
          jwk-set-uri: http://localhost:9065/auth/realms/fast-payment/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG

keycloak:
  realm: fast-payment
  auth-server-url: http://localhost:9065
  resource: fast-payment
  credentials:
    secret: 3dUyOoZlIakzZiZ3QqPyIA73dcFC3Z5D
  public-client: true
  use-resource-role-mappings: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true  # Ensures the service registers with Eureka
    fetchRegistry: true        # Fetches the registry from Eureka

server:
  port: 7072  # Port on which the application will run

management:
  tracing:
    sampling:
      probability: 1.0
