apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-payment-service
  labels:
    app: order-payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-payment-service
  template:
    metadata:
      labels:
        app: order-payment-service
    spec:
      containers:
      - name: order-payment-service
        image: bickyrajkayastha/fast-payment-order-payment-service:d410ab93cc3fe58e707e6bfa7cf1e5f3e10b4e38
        imagePullPolicy: Always
        ports:
        - containerPort: 7074
