apiVersion: v1
kind: Service
metadata:
  name: order-payment-service
  labels:
    app: order-payment-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7074         # Exposes the service on port 80
      targetPort: 7074  # The port on the container
#      nodePort: 31000
  selector:
    app: order-payment-service
