spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/delivery_service_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Options: validate | update | create | create-dro
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.yaml
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
server:
  port: 7079
