spring:
  rabbitmq:
    host: rabbitmq
    port: 5672

  datasource:
    url: jdbc:postgresql://postgres:5432/demospring_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Options: validate | update | create | create-drop

  elasticsearch:
    uris: http://elasticsearch:9200

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: fast-payment
            client-secret: B5AROsL8nOKhoyjTS1X8jTmwKxJDyFb9
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: "openid,profile,email"
        provider:
          keycloak:
            issuer-uri: http://keycloak:9065/realms/fast-payment
            user-info-uri: http://keycloak:9065/realms/fast-payment/protocol/openid-connect/userinfo
            token-uri: http://keycloak:9065/realms/fast-payment/protocol/openid-connect/token
            authorization-uri: http://keycloak:9065/realms/fast-payment/protocol/openid-connect/auth
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9065/auth/realms/fast-payment
#          jwk-set-uri: http://keycloak:9065/auth/realms/fast-payment/protocol/openid-connect/certs
          jwk-set-uri:  http://keycloak:9065/realms/fast-payment/protocol/openid-connect/certs
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    io.micrometer.tracing: DEBUG
    brave: DEBUG
    org.springframework.security: DEBUG

keycloak:
  realm: fast-payment
  auth-server-url: http://keycloak:9065
  resource: fast-payment
  credentials:
    secret: B5AROsL8nOKhoyjTS1X8jTmwKxJDyFb9
  public-client: true
  use-resource-role-mappings: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    registerWithEureka: true   # Ensures the service registers with Eureka
    fetchRegistry: true         # Fetches the registry from Eureka

minio:
  endpoint: http://minio:9000
  access-key: IRFfzxAIqS8V6tGSR5Ml
  secret-key: dfLqi2GKyhAv7Q17NbzOtVKpuwoGWcPGuybFLmjk
  region: us-east-1
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
