spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/reporting_db
      database: reporting_db
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: fast-payment
            client-secret: B5AROsL8nOKhoyjTS1X8jTmwKxJDyFb9
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://keycloak:9065/realms/fast-payment
            user-info-uri: http://keycloak:9065/realms/fast-payment/protocol/openid-connect/userinfo
            token-uri: http://keycloak:9065/realms/fast-payment/protocol/openid-connect/token
            authorization-uri: http://keycloak:9065/realms/fast-payment/protocol/openid-connect/auth
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9065/realms/fast-payment
          jwk-set-uri:  http://keycloak:9065/realms/fast-payment/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: kafka-2:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: report-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        cloud:
          gateway: DEBUG
        boot:
          web:
            servlet:
              FilterRegistrationBean: TRACE

keycloak:
  realm: fast-payment
  auth-server-url: http://keycloak:9065
  resource: fast-payment
  credentials:
    secret: B5AROsL8nOKhoyjTS1X8jTmwKxJDyFb9
  public-client: true
  use-resource-role-mappings: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0