spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/reporting_db
      database: reporting_db
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: fast-payment
            client-secret: XDOu8eVWloZmlc4Qt9wwRFvzfVN3pvzp
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri:  http://localhost:9065/realms/fast-payment
            user-info-uri:  http://localhost:9065/realms/fast-payment/protocol/openid-connect/userinfo
            token-uri:  http://localhost:9065/realms/fast-payment/protocol/openid-connect/token
            authorization-uri:  http://localhost:9065/realms/fast-payment/protocol/openid-connect/auth
      resourceserver:
        jwt:
          issuer-uri:  http://localhost:9065/auth/realms/fast-payment
#          jwk-set-uri:  http://localhost:9065/auth/realms/fast-payment/protocol/openid-connect/certs
          jwk-set-uri:  http://localhost:9065/realms/fast-payment/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: report-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"   # Trust all packages for deserialization
        spring.kafka.consumer.value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.kafka.consumer.properties.spring.json.value.default.type: com.bicky.demopayment.sharedmodule.dto.PaymentEvent
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        cloud:
          gateway: DEBUG
        boot:
          web:
            servlet:
              FilterRegistrationBean: TRACE

keycloak:
  realm: fast-payment
  auth-server-url:  http://localhost:9065
  resource: fast-payment
  credentials:
    secret: YV7BQhesXAof0e0vgHdXZc4tkddJ4Zby
  public-client: true
  use-resource-role-mappings: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0