server:
  address: 0.0.0.0
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/
  profiles:
    active: native