apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3030         # Exposes the service on port 80
      targetPort: 3030  # The port on the container
#      nodePort: 30003
  selector:
    app: api-gateway
