apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  labels:
    app: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: bickyrajkayastha/fast-payment-report-service:2ab7af793e9290cfe5fbd3aee6957380c11dc8b4
        imagePullPolicy: Always
        ports:
        - containerPort: 7026
