apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: bickyrajkayastha/fast-payment-order-service:c0c9ca93b3be7fa49a3423c52c083841d86b0f4f
        imagePullPolicy: Always
        ports:
        - containerPort: 7072
