apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: bickyrajkayastha/fast-payment-order-service:c87b22684fec37843a2e5689a0ba96a3dc484bf5
        imagePullPolicy: Always
        ports:
        - containerPort: 7072
