apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7072         # Exposes the service on port 80
      targetPort: 7072  # The port on the container
#      nodePort: 31000
  selector:
    app: order-service
