
name: Build and Push Docker Image for config-server

# This workflow triggers on pushes to the main branch or specific changes in the 'notification-service' directory
on:
  push:
    branches:
      - main  # Trigger on push to main branch
    paths:
      - 'config-server/**'  # Only trigger when changes happen in this directory
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional, but useful for multi-architecture builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use the secret stored in GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use the secret stored in GitHub

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fast-payment-config-server:latest ./config-server
          docker tag ${{ secrets.DOCKER_USERNAME }}/fast-payment-config-server:latest ${{ secrets.DOCKER_USERNAME }}/fast-payment-config-server:${{ github.sha }}

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fast-payment-config-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fast-payment-config-server:${{ github.sha }}
      
      # Step 6: Update Kubernetes Deployment YAML with SHA-tagged image
      - name: Update Kubernetes Deployment with new image SHA tag
        run: |
          # Replace the image tag in the deployment YAML with the new SHA
          sed -i 's|image: .*fast-payment-config-server:.*|image: ${{ secrets.DOCKER_USERNAME }}/fast-payment-config-server:${{ github.sha }}|' k8/config-server/deployment.yml

      # Step 7: Commit and push the updated Kubernetes YAML file
      - name: Commit the changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git add k8/config-server/deployment.yml
          git commit -m "Update config-server image to ${GITHUB_SHA}"
          git push origin main

