name: Build and Push Docker Image

# This workflow triggers on pushes to the main branch or specific changes in the 'notification-service' directory
on:
  push:
    branches:
      - main  # Trigger on push to main branch
    paths:
      - 'notification-service/**'  # Only trigger when changes happen in this directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional, but useful for multi-architecture builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use the secret stored in GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use the secret stored in GitHub

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fast-payment-notification-service:latest ./notification-service
          docker tag ${{ secrets.DOCKER_USERNAME }}/fast-payment-notification-service:latest ${{ secrets.DOCKER_USERNAME }}/fast-payment-notification-service:${{ github.sha }}

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fast-payment-notification-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fast-payment-notification-service:${{ github.sha }}

