apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: bickyrajkayastha/fast-payment-notification-service:bc7db7e187abaeaeb145cd529bb784f2609ca120
        imagePullPolicy: Always
        ports:
        - containerPort: 7022
