apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: bickyrajkayastha/fast-payment-notification-service:3cf89a280269277fd7af9967a6d790c05b663b44
        imagePullPolicy: Always
        ports:
        - containerPort: 7022
