apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: bickyrajkayastha/fast-payment-notification-service:ace1aebf057f9b21a39b31bb0409514e8ff241f6
        imagePullPolicy: Always
        ports:
        - containerPort: 7022
